---

- name: Initialize Celestia Light
  shell: |
    celestia light init --p2p.network blockspacerace
  args:
    chdir: "{{ ansible_user_dir }}/celestia-node"
  register: celestia_light_init_output

- name: Print Celestia Light output
  debug:
    var: celestia_light_init_output

- name: Create Celestia Light systemd service file
  become: true
  shell: |
    sudo tee <<EOF >/dev/null /etc/systemd/system/celestia-lightd.service
    [Unit]
    Description=celestia-lightd Light Node
    After=network-online.target
    
    [Service]
    User={{ ansible_user }}
    ExecStart=/usr/local/bin/celestia light start --core.ip https://rpc-blockspacerace.pops.one/ --core.grpc.port 9090 --gateway --gateway.addr localhost --gateway.port 26659 --metrics.tls=false --metrics --metrics.endpoint otel.celestia.tools:4318 --p2p.network blockspacerace
    Restart=on-failure
    RestartSec=3
    LimitNOFILE=4096
    
    [Install]
    WantedBy=multi-user.target
    EOF

- name: Enable Celestia Light systemd service
  become: true
  systemd:
    name: celestia-lightd
    enabled: yes

- name: Start Celestia Light systemd service
  become: true
  systemd:
    name: celestia-lightd
    state: started

- name: Get Celestia Light authentication token
  become: true
  shell: |
    celestia light auth admin --p2p.network blockspacerace
  register: auth_token

- name: Call p2p.Info method via Celestia Light API
  become: true
  shell: |
    curl -X POST \
         -H "Authorization: Bearer {{ auth_token.stdout }}" \
         -H 'Content-Type: application/json' \
         -d '{"jsonrpc":"2.0","id":0,"method":"p2p.Info","params":[]}' \
         http://localhost:26658
  register: p2p_info

- name: Print p2p.Info method output
  debug:
    var: p2p_info.stdout
