---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - curl
      - git
      - jq
      - lz4
      - build-essential
    state: latest

- name: Upgrade packages
  apt:
    upgrade: dist
    update_cache: yes
    autoremove: yes
